### DISCUSSION TITLE
Background

### DISCUSSION THREAD

**Discussion by Zipp0KMS** [marcokreeft87/room-card#100] [Q&A] [answered]
Hey. Thank you for your work!
Is it possible to add a background to the entire card like custom:minimalistic-area-card?

**Comment by marcokreeft87** [comment, marked as answer]
Yes you can by setting this on the main entity:

```
styles: 
  background-image: url('https://images.pexels.com/photos/235986/pexels-photo-235986.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1')
```

**Reply by Zipp0KMS** [reply]
It works, thanks :)
But I'm a noob in css. How I can render the full image at the size of the card? I have only a small part of the image in the card, now.

**Reply by Zipp0KMS** [reply]
![Screenshot_20221014-141235_Home Assistant](https://user-images.githubusercontent.com/97192615/195844140-9c9ed62d-5df8-4a11-8215-4da3f1183e6e.png)

I didn't get it... if I use "height" under "styles", it change the entire card height, not the image.

**Comment by marcokreeft87** [comment]
I think your images is too small than but you can find all you need here : https://www.w3schools.com/cssref/pr_background-image.asp

**Comment by FlexxFR** [comment]
How to get the additional card transparent/semi-transparent to see the background picture (as example pic above)
I get:
![image](https://user-images.githubusercontent.com/65705235/204054325-01cf23e8-9ecd-4023-8486-75db4ff5ee42.png)

**Comment by marcokreeft87** [comment]
You have to configure that card

**Comment by FlexxFR** [comment]
all right, I figured it out. 

Added this to the 2nd card

```
          style:
            .: |
              ha-card {
                background-color: transparent !important;
                box-shadow: none !important;
              }
```

However, every time the main card is updated (for example the motion icon), the subcard flashes white for a split second before turning transparent again.  Is this something that can be fixed?

**Reply by marcokreeft87** [reply]
Not sure. Will try and reproduce it. Can you send me your yaml?

**Comment by FlexxFR** [comment]
This is was I use for testing

```
type: custom:room-card
title: Zolder
entity: light.attic
icon: mdi:home-floor-a
show_icon: true
styles:
  background-image: url('https://demo.home-assistant.io/stub_config/kitchen.png')
tap_action:
  action: toggle
info_entities:
  - entity: group.motion_zolder_studeer1
    show_icon: true
    state_color: true
    tap_action:
      action: toggle
  - entity: group.motion_zolder_studeer2
    show_icon: true
    tap_action:
      action: toggle
entities:
  - entity: group.motion_zolder_studeer3
    show_icon: true
    tap_action:
      action: toggle
  - entity: light.snfesp_slaapkamer_light
    name: Plafond
    show_icon: true
    show_name: true
    tap_action:
      action: toggle
  - entity: sensor.temperatuur_slaapkamer_avg
    name: ddd
    icon: mdi:temperature-celsius
    show_icon: true
    show_name: true
    tap_action:
      action: toggle
    styles:
      entity:
        - font-size: 20px
        - color: white
cards:
  - type: entity
    entity: sensor.temperatuur_slaapkamer_avg
    style:
      .: |
        ha-card {
          background-color: transparent !important;
          box-shadow: none !important;
          border-style: none;
        }
```
