### DISCUSSION TITLE
Possible to use an entity attribute in templating?

### DISCUSSION THREAD

**Discussion by Leticron** [marcokreeft87/room-card#152] [Q&A]
Hi, 

first of all, thank you for this custom card - it is simply awesome. 

I am redoing my dashboard thanks to your card and I usually work heavily with templates. 
However, one thing I could not figure out is the use of an entity's attribute in a template. 

```
type: custom:room-card
title: Hallway
icon: mdi:door-closed-lock
show_icon: true
templates:
  - name: test_template
    template:
      show_icon: true
      state_color: true
      icon:
      template:
        styles: >
          if (entity.state >= 70) return 'color: green';  if (entity.state >=
          20) return 'color: orange';  else return 'color: orangered';
```

the `entity.state >= 70` in the if statement made me wondering if I could specify the attribute here as well. 
So far using Jinja2 templating did not work for me, e.g. `{{ state_attr("sensor.xyz", "attribute1") }}` is not resolvable.

Any suggestions/thoughts are welcome. 

Thanks
