### DISCUSSION TITLE
Is it possible to change icon and color when the entity state is "unavailable"?

### DISCUSSION THREAD

**Discussion by diegofrances** [marcokreeft87/room-card#340] [Q&A]
Hello All,

I have some Sonoff S60TPF Smart Plugs that I would like to monitor using the "info_entities:" option. I would like to know when the microwave is idle, working and when there is an energy cut.

I came up with an idea and I have tried the below but does not seem to recognize the "unavailable" state of the entity.

type: custom:room-card
title: Kitchen
info_entities:
  - entity: sensor.sonoff_microwave_power
    show_icon: true
    icon:
      template:
        styles: >
          if (entity.state == 'unavailable') return 'color: rgb(255, 0, 0)';
		  else if (entity.state > 90) return 'color: rgb(255, 165, 0)';
		  else if (entity.state < 90) return 'color: rgb(255, 0, 0)'; 
        icon: >
          if (entity.state == 'unavailable') return 'mdi:microwave-off';
		  else return 'mdi:microwave';

Is the "unavailable" state not part of "room-card" customization? If this is the case, is there any other option?

Thank you in advance.

Regards,
Diego

**Comment by marcokreeft87** [comment]
You might want to take a look at icon conditions

**Comment by diegofrances** [comment]
Hello @marcokreeft87,

Thank you for your quick answer and your suggestion.

I have been able to change the icon based on the status of the entity; tested and works as expected.

Please find what I have included on my card:

type: custom:room-card
title: Kitchen
info_entities:
  - entity: sensor.sonoff_microwave_power
    show_icon: true
    icon:
      conditions:
        - icon: mdi:microwave-off
          condition: equals
          entity: sensor.sonoff_microwave_power
          value: unavailable
        - icon: mdi:microwave
          condition: not_equals
          entity: sensor.sonoff_microwave_power
          value: unavailable


Unfortunately I am not able to combine icon type and color. Please find what I have tried.

type: custom:room-card
title: Kitchen
info_entities:
  - entity: sensor.sonoff_microwave_power
    show_icon: true
    icon:
      conditions:
        - icon: mdi:microwave-off
          condition: equals
          entity: sensor.sonoff_microwave_power
          value: unavailable
        - icon: mdi:microwave
          condition: not_equals
          entity: sensor.sonoff_microwave_power
          value: unavailable
        - condition: below
          value: 90
          styles:
            color: rgb(0, 255, 0)
			
The above shows the desired icon's color but the default entity's icon.

If the entity state is "unavailable", icon has to be "mdi:microwave-off" and color red but if entity´s state is different from "unavailable" the icon has to be "mdi:microwave" and color orange if the value is above 90 and color green if the value is below 90.

Can you please help me to achieve what I want/need?

Thank you in advance.

**Reply by marcokreeft87** [reply]
Try this 

```- entity: sensor.node_21_humidity
  show_icon: true
  icon:
    conditions:
      - icon: mdi:car
        condition: above
        value: 20
      - icon: mdi:car-2-plus
        condition: above
        value: 30
      - icon: mdi:car-3-plus
        condition: below
        value: 50
      - icon: mdi:car-arrow-left
        condition: equals
        attribute: state
        value: 35.6      
      - icon: phu:lift-in-window-open1
        condition: above
        entity: sensor.bathroom1_window_sensor_tilt
        value: 0
      - condition: above
        value: 70
        styles:
          color: green

**Comment by diegofrances** [comment]
Tried the following but the unavailable state does not have the red color

```
      conditions:
        - condition: equals
          value: unavailable
          icon: mdi:microwave-off
          styles:
            color: rgb(255, 0, 0)
        - condition: below
          value: 90
          icon: mdi:microwave
          styles:
            color: rgb(0, 255, 0)
        - condition: above
          value: 90
          icon: mdi:microwave
          styles:
            color: rgb(255, 165, 0)
```
