### DISCUSSION TITLE
More information under icon

### DISCUSSION THREAD

**Discussion by Widda** [marcokreeft87/room-card#60] [Q&A]
Hi!
Would it be possible to show for example how much energy a light is having when it is powerd under the icon? For example watt or maybe any attribute regarding to that entity. Maybe multiple rows? Like your example on Printer info on toner Black.

**Comment by marcokreeft87** [comment]
Yes you can with icon templates. Check the wiki :)

**Comment by Widda** [comment]
Hi!
I have now tried to fix this and now the info under icon changes to ON and not the state on w. See video.
I also tested to get the icon to light up as soon as i click on icon but that one don't work.
What have i done wrong?
Here is my code on card.

```
type: custom:room-card
title: Badrum
entity: switch.badrum_lampor
icon: mdi:lightbulb-outline
show_icon: false
state_color: true
entities:
  - entity: switch.badrum_brytare_1_spegel_light
    name: Spegel
    state_color: true
    tap_action:
      action: toggle
  - entity: sensor.badrum_brytare_1_spegel_light_electric_consumption_w
    name: Spegel
    show_state: true
    show_icon: true
    tap_action:
      action: call-service
      service: homeassistant.toggle
      service_data:
        entity_id: switch.badrum_brytare_1_spegel_light
    icon:
      template:
        styles: >
          if (entity.state > 0) return 'color:
          var(--paper-item-icon-active-color)';          
        icon: |
          return 'mdi:mirror-rectangle';
  - entity: sensor.badrum_brytare_1_spegel_light_electric_consumption_w
    name: Spegel
    show_state: true
    show_icon: true
    tap_action:
      action: call-service
      service: homeassistant.toggle
      service_data:
        entity_id: switch.badrum_brytare_1_spegel_light
    icon:
      entity: switch.badrum_brytare_1_spegel_light
      template:
        styles: >
          if (entity.state = 'on') return 'color:
          var(--paper-item-icon-active-color)';
        icon: |
          return 'mdi:mirror-rectangle';
  - entity: sensor.badrum_brytare_1_spegel_light_electric_consumption_w
    name: w
    show_state: true
    show_icon: false
  - entity: switch.badrum_brytare_1_flakt
    name: Fläkt
    state_color: true
    tap_action:
      action: toggle
  - entity: switch.badrum_handdukstork
    name: Handdukstork
    state_color: true
    tap_action:
      action: toggle
  - entity: sensor.badrum_handdukstork_electric_consumption_w
    name: w
    show_state: true
    show_icon: false
  - entity: switch.pannrum_varmvatten
    name: Varmvatten
    state_color: true
    tap_action:
      action: toggle
info_entities:
  - entity: binary_sensor.badrum_multisensor_6_home_security_motion_detection
    show_icon: true
    state_color: true
  - sensor.badrum_multisensor_6_luminance
  - sensor.badrum_multisensor_6_relative_humidity
  - entity: sensor.badrum_multisensor_6_temperature
    format: precision1
  - entity: sensor.badrum_multisensor_6_battery_level
    show_icon: true

```

https://user-images.githubusercontent.com/15378557/193458841-2151c48e-1fa8-49d4-a767-7775c20e713b.mov
