### ISSUE TITLE
Handling of Buttons changed

### ISSUE THREAD

**Issue by dhzl84** [marcokreeft87/room-card#109]
**Which version of Room Card?**
v1.07.00

**Describe the bug**
I used to use the `tap_action` `toggle` to activate a `button`.
Today I got an error message from HA that the service `button/turn_off` is not supported.

My Card Config:

```
type: custom:room-card
title: Draußen
show_state: false
info_entities:
  - sensor.temperatur_aussensensor
  - sensor.luftfeuchtigkeit_aussensensor
entities:
  - entity: button.garagentor
    tap_action:
      action: toggle

```

**To Reproduce**
Use a button with toggle

**Expected behavior**
Either toggle works for `button`, or a new action `press` is added specifically for buttons

** Containment Action **
I use a service call to press the button:
```
type: custom:room-card
title: Draußen
show_state: false
info_entities:
  - sensor.temperatur_aussensensor
  - sensor.luftfeuchtigkeit_aussensensor
entities:
  - entity: button.garagentor
    tap_action:
      action: call-service
      service: button.press
      service_data:
        entity_id: button.garagentor

```
