### ISSUE TITLE
input_boolean forced to on if it's the main entity

### ISSUE THREAD

**Issue by hugalafutro** [marcokreeft87/room-card#110]
**Which version of Room Card?**
1.07.00

**Describe the bug**
if the main entity is `input_boolean` it will be forced to on upon switching to off with no record in logbook, like so:
```
type: custom:stack-in-card
cards:
  - type: custom:room-card
    title: Media
    entity: input_boolean.helper_room_card_viglen_sleep
    tap_action:
      action: more-info
    show_icon: true
    icon:
      template:
        icon: |
          if (entity.state = 'on') return ' ';   else return 'mdi:sleep';
    rows:
      - entities:
          - entity: script.turboviglen_monitor_primary
            name: Primary
            tap_action:
              action: toggle

... etc etc
```

**To Reproduce**
1. choose any input_boolean helper as main entity
2. try to turn the helper off from anywhere
3. wait a sec
4. look how it goes on by itself

**Expected behavior**
card should not affect state of entity

**Screenshots**
https://o.o5.ddns.net/ha_toggle

**Desktop (please complete the following information):**
 - OS: win11
 - Browser chrome
 - Version latest vivaldi

**Additional context**
I was playing with hiding the icon of the main entity as per the discussion on ha community forum, and was running into issue where the button entity I used had no state on/off, but was either unavailable or had a string of last timestamp when pressed in it and I couldn't work out the conditions, so I was trying to create a helper input_boolean toggle to use with a helper automation to control the button via entity with 0/1 state, but when I put the input_boolean into main entity I noticed it never turns to off state even when pressed goes back to on immediately.
