### ISSUE TITLE
Toggle icon colour when thermostat is heating

### ISSUE THREAD

**Issue by EmmanuelLM** [marcokreeft87/room-card#114]
Hi, it would be great if a thermostat device icon colour could change when the device is in heating (and maybe even toggle between heat and off when clicked).

Thanks

**Comment by marcokreeft87** [comment]
Have you checked the wiki? Check out icon conditions

**Comment by EmmanuelLM** [comment]
Maybe I am being slow, but tried this and didn't see to work when
climate.middle_bathroom_thermostat state was 'heat'

type: custom:room-card
title: Second Bathroom
icon: mdi:shower
entity: switch.second_bathroom_switch_l1
show_icon: true
entities:
  - entity: switch.second_bathroom_switch_l1
    name: Light
    icon: mdi:light-recessed
    state_color: 'on'
    show_icon: true
    tap_action:
      action: toggle
  - entity: switch.second_bathroom_switch_l2
    name: Fan
    icon: mdi:fan
    state_color: 'on'
    show_icon: true
    tap_action:
      action: toggle
  - entity: climate.middle_bathroom_thermostat
    name: Thermostat
    show_icon: true
    icon:
      conditions:
        - condition: equals
          attribute: state
          value: heat
          styles:
            color: orange
info_entities:
  - entity: sensor.middle_bathroom_thermostat_external_temperature

**Comment by marcokreeft87** [comment]
I'm doing exactly the same here:

```
- entity: climate.radiator_mancave
    name: Radiator
    show_icon: true
    icon:
      conditions:
        - condition: equals
          value: heat
          icon: mdi:radiator
          styles:
            color: orange;
```
