### ISSUE TITLE
Tap action not working on card title

### ISSUE THREAD

**Issue by nbanbury** [marcokreeft87/room-card#12]
Hi there - love the card, thanks. Seems I can't get the tap-action to work however. My code is as follows:

type: entities
title: Upstairs Lights
entity: light.upstairs
tap-action:
  action: toggle
icon: mdi:lightbulb-group

Clicking anywhere in the title area has no effect.

**Comment by marcokreeft87** [comment]
That's probably because the Tap action is on the icon

**Comment by marcokreeft87** [comment]
Thats weird. I have the same config. Can you send the full yaml?

**Comment by nbanbury** [comment]
Will do. I'll double check it all first!

**Comment by nbanbury** [comment]
Hi there. I've checked and tried again but no joy.  The tap action works fine on individual lights but not on the title icon (for me).

Here's the full YAML:

type: entities
title: Downstairs Lights
entity: light.downstairs
tap-action:
  action: toggle
icon: mdi:lightbulb-group
entities:
  - type: custom:room-card
    title: Living Room
    entities:
      - entity: light.living_room
        name: All lights
        state_color: true
        icon:
          state_on: mdi:lamps
          state_off: mdi:lamps-outline
      - entity: light.tall_lamp
        name: Tall Lamp
        state_color: true
        icon:
          state_on: mdi:floor-lamp
          state_off: mdi:floor-lamp-outline
        tap_action:
          action: toggle
      - entity: light.brown_lamp
        name: Brown Lamp
        state_color: true
        icon:
          state_on: mdi:lamp
          state_off: mdi:lamp-outline
        tap_action:
          action: toggle
      - entity: light.tripod_lamp
        name: Tripod Lamp
        state_color: true
        icon:
          state_on: mdi:floor-lamp-torchiere-variant
          state_off: mdi:floor-lamp-torchiere-variant-outline
        tap_action:
          action: toggle
      - entity: switch.lava_lamp_mss210_main_channel
        name: Lava Lamp
        state_color: true
        icon:
          state_on: mdi:lava-lamp
          state_off: mdi:desk-lamp-off
        tap_action:
          action: toggle
      - entity: switch.aquarium_smart_plug_mss210_main_channel
        name: Aquarium
        tap_action:
          action: toggle
        state_color: true
        icon:
          state_on: mdi:fishbowl
          state_off: mdi:fishbowl-outline
  - type: custom:room-card
    title: Kitchen
    entities:
      - entity: light.kitchen
        name: All lights
        state_color: true
        icon:
          state_on: mdi:lightbulb-group
          state_off: mdi:lightbulb-group-off
      - entity: light.kitchen_lamp
        name: Lamp
        state_color: true
        icon:
          state_on: mdi:lightbulb-on
          state_off: mdi:lightbulb-off
        tap_action:
          action: toggle
      - entity: light.kitchen_spot_1
        name: Spot 1
        state_color: true
        icon:
          state_on: mdi:lightbulb-spot
          state_off: mdi:lightbulb-spot-off
        tap_action:
          action: toggle
      - entity: light.kitchen_spot_2
        name: Spot 2
        state_color: true
        icon:
          state_on: mdi:lightbulb-spot
          state_off: mdi:lightbulb-spot-off
        tap_action:
          action: toggle
      - entity: light.kitchen_spot_3
        name: Spot 3
        state_color: true
        icon:
          state_on: mdi:lightbulb-spot
          state_off: mdi:lightbulb-spot-off
        tap_action:
          action: toggle
      - entity: light.kitchen_spot_4
        name: Spot 4
        state_color: true
        icon:
          state_on: mdi:lightbulb-spot
          state_off: mdi:lightbulb-spot-off
        tap_action:
          action: toggle
  - type: custom:room-card
    title: Front Room
    entities:
      - entity: light.front_room_lamp
        name: Table Lamp
        state_color: true
        icon:
          state_on: mdi:lightbulb-on
          state_off: mdi:lightbulb-off
        tap_action:
          action: toggle
      - entity: light.front_room_wall_lamp
        name: Wall Lamp
        state_color: true
        icon:
          state_on: mdi:lightbulb-on
          state_off: mdi:lightbulb-off
        tap_action:
          action: toggle
  - type: custom:room-card
    title: Hall, Porch and Outside
    entities:
      - entity: light.hall_lamp
        name: Hall Lamp
        state_color: true
        icon:
          state_on: mdi:lightbulb-on
          state_off: mdi:lightbulb-off
        tap_action:
          action: toggle
      - entity: light.porch
        name: Porch
        state_color: true
        icon:
          state_on: mdi:lightbulb-on
          state_off: mdi:lightbulb-off
        tap_action:
          action: toggle
      - entity: light.outside
        name: Outside Wall
        state_color: true
        icon:
          state_on: mdi:outdoor-lamp
          state_off: mdi:outdoor-lamp
        tap_action:
          action: toggle
      - entity: switch.shed_mss210_main_channel
        name: Outside Spots
        state_color: true
        icon:
          state_on: mdi:track-light
          state_off: mdi:track-light-off
        tap_action:
          action: toggle

**Comment by marcokreeft87** [comment]
Hmm nothing weird in the yaml. Can you try a room-card with being in the entities card? Thats the only difference I could think off

**Comment by nbanbury** [comment]
Not sure what you mean - do mean change the first card to custom:room-card?

**Comment by marcokreeft87** [comment]
Yes copy and paste the room card yaml so there will be one room card above the entities card. So above type: entities

**Comment by nbanbury** [comment]
I tried with the code above and it isn't working (just get the spinning icon and a blurred preview).

I had a play around and added some indentation, as per the code below.

```
type: custom:room-card
title: Downstairs Lights
entity: light.downstairs
icon: mdi:lightbulb-group
tap-action:
   action: toggle
entities:
  - type: entities
    title: Downstairs Lights
    entity: light.downstairs
    icon: mdi:lightbulb-group
    tap-action:
      action: toggle
    entities:
      - type: custom:room-card
        title: Living Room
        entities:
          - entity: light.living_room
            name: All lights
            state_color: true
            icon:
              state_on: mdi:lamps
              state_off: mdi:lamps-outline
          - entity: light.tall_lamp
            name: Tall Lamp
            state_color: true
            icon:
              state_on: mdi:floor-lamp
              state_off: mdi:floor-lamp-outline
            tap_action:
              action: toggle
          - entity: light.brown_lamp
            name: Brown Lamp
            state_color: true
            icon:
              state_on: mdi:lamp
              state_off: mdi:lamp-outline
            tap_action:
              action: toggle
          - entity: light.tripod_lamp
            name: Tripod Lamp
            state_color: true
            icon:
              state_on: mdi:floor-lamp-torchiere-variant
              state_off: mdi:floor-lamp-torchiere-variant-outline
            tap_action:
              action: toggle
          - entity: switch.lava_lamp_mss210_main_channel
            name: Lava Lamp
            state_color: true
            icon:
              state_on: mdi:lava-lamp
              state_off: mdi:desk-lamp-off
            tap_action:
              action: toggle
          - entity: switch.aquarium_smart_plug_mss210_main_channel
            name: Aquarium
            tap_action:
              action: toggle
            state_color: true
            icon:
              state_on: mdi:fishbowl
              state_off: mdi:fishbowl-outline
      - type: custom:room-card
        title: Kitchen
        entities:
          - entity: light.kitchen
            name: All lights
            state_color: true
            icon:
              state_on: mdi:lightbulb-group
              state_off: mdi:lightbulb-group-off
          - entity: light.kitchen_lamp
            name: Lamp
            state_color: true
            icon:
              state_on: mdi:lightbulb-on
              state_off: mdi:lightbulb-off
            tap_action:
              action: toggle
          - entity: light.kitchen_spot_1
            name: Spot 1
            state_color: true
            icon:
              state_on: mdi:lightbulb-spot
              state_off: mdi:lightbulb-spot-off
            tap_action:
              action: toggle
          - entity: light.kitchen_spot_2
            name: Spot 2
            state_color: true
            icon:
              state_on: mdi:lightbulb-spot
              state_off: mdi:lightbulb-spot-off
            tap_action:
              action: toggle
          - entity: light.kitchen_spot_3
            name: Spot 3
            state_color: true
            icon:
              state_on: mdi:lightbulb-spot
              state_off: mdi:lightbulb-spot-off
            tap_action:
              action: toggle
          - entity: light.kitchen_spot_4
            name: Spot 4
            state_color: true
            icon:
              state_on: mdi:lightbulb-spot
              state_off: mdi:lightbulb-spot-off
            tap_action:
              action: toggle
      - type: custom:room-card
        title: Front Room
        entities:
          - entity: light.front_room_lamp
            name: Table Lamp
            state_color: true
            icon:
              state_on: mdi:lightbulb-on
              state_off: mdi:lightbulb-off
            tap_action:
              action: toggle
          - entity: light.front_room_wall_lamp
            name: Wall Lamp
            state_color: true
            icon:
              state_on: mdi:lightbulb-on
              state_off: mdi:lightbulb-off
            tap_action:
              action: toggle
      - type: custom:room-card
        title: Hall, Porch and Outside
        entities:
          - entity: light.hall_lamp
            name: Hall Lamp
            state_color: true
            icon:
              state_on: mdi:lightbulb-on
              state_off: mdi:lightbulb-off
            tap_action:
              action: toggle
          - entity: light.porch
            name: Porch
            state_color: true
            icon:
              state_on: mdi:lightbulb-on
              state_off: mdi:lightbulb-off
            tap_action:
              action: toggle
          - entity: light.outside
            name: Outside Wall
            state_color: true
            icon:
              state_on: mdi:outdoor-lamp
              state_off: mdi:outdoor-lamp
            tap_action:
              action: toggle
          - entity: switch.shed_mss210_main_channel
            name: Outside Spots
            state_color: true
            icon:
              state_on: mdi:track-light
              state_off: mdi:track-light-off
            tap_action:
              action: toggle
```

Unfortunately still no luck, this is the output:
![image](https://user-images.githubusercontent.com/26057238/188091848-33ce9755-96aa-4bc0-86a8-b1341402e461.png)

The issue isn't hugely important in the scheme of things, but would love to get to the bottom of it! Thanks.
