### ISSUE TITLE
Add 'AND' for hide_if conditions

### ISSUE THREAD

**Issue by Blacksli** [marcokreeft87/room-card#120]
**Is your feature request related to a problem? Please describe.**
no

**Have you tried if it is already a feature? Have you checked the wiki?**
yes

**Describe the solution you'd like**
Add 'AND' for conditions

I am using lighting objects.
I have a chandelier with 2 groups of lamps.
I would like to display a row with additional lighting information if one of the two groups of lamps is enabled.
Now I can only configure if both are enabled

**Comment by Blacksli** [comment]
> Cant you just make 2 conditions? One for each group of lamps?

can you help me?

```
rows:
  - entities:
      - entity: light.zal_liustra_2_lampy
        name: Люстра 2
        tap_action:
          action: toggle
        icon: mdi:ceiling-light
        show_icon: true
      - entity: light.zal_liustra_4_lampy
        name: Люстра 4
        tap_action:
          action: toggle
        icon: mdi:ceiling-light-multiple
        show_icon: true
  - entities:
      - entity: sensor.0x00158d0005c0e34b_current
        name: current
        show_state: true
        show_icon: false
      - entity: sensor.zal_light_power
        name: Power
        show_state: true
        show_icon: false
      - entity: sensor.0x00158d0005c0e34b_voltage_2
        name: V
        show_state: true
        show_icon: false
      - entity: sensor.zal_lustra_energy
        name: Energy
        show_state: true
        show_icon: false
    hide_if:
      conditions:
        - condition: equals
          entity: light.zal_liustra_4_lampy
          value: 'off'
```

**Comment by marcokreeft87** [comment]
```
rows:
  - entities:
      - entity: light.zal_liustra_2_lampy
        name: Люстра 2
        tap_action:
          action: toggle
        icon: mdi:ceiling-light
        show_icon: true
      - entity: light.zal_liustra_4_lampy
        name: Люстра 4
        tap_action:
          action: toggle
        icon: mdi:ceiling-light-multiple
        show_icon: true
  - entities:
      - entity: sensor.0x00158d0005c0e34b_current
        name: current
        show_state: true
        show_icon: false
      - entity: sensor.zal_light_power
        name: Power
        show_state: true
        show_icon: false
      - entity: sensor.0x00158d0005c0e34b_voltage_2
        name: V
        show_state: true
        show_icon: false
      - entity: sensor.zal_lustra_energy
        name: Energy
        show_state: true
        show_icon: false
    hide_if:
      conditions:
        - condition: equals
          entity: light.zal_liustra_4_lampy
          value: 'off'
        - condition: equals
          entity: light.zal_liustra_2_lampy
          value: 'off'
```

try this
