### ISSUE TITLE
How to show Attributes

### ISSUE THREAD

**Issue by tamueller** [marcokreeft87/room-card#122]
**Which version of Room Card?**
1.07.03

**Describe the bug**
I would like to show the attribute of an entity instead of the entity icon, but it does not work (or I don't know the correct syntax for it). The wiki does not have any examples where the attribute is shown directly, only examples where the attribute is used in a condition.

I have this card, and would expect to see the brightness, but I get the lamp-icon instead.
```
type: custom:room-card
title: Wohnzimmer
entities:
  - entity: light.licht_wohnzimmer_decke
    attribute: brightness
    name: Decke
info_entities:
```

I also tried `attribute: light.licht_wohnzimmer_decke.brightness` but it didn't work either. How can I display a specific attribute instead of the state-icon.

Thanks for the help.

**Comment by marcokreeft87** [comment]
```
type: custom:room-card
entities:
  - entity: light.lamp_tafel
    show_icon: false
    show_state: true
    attribute: brightness


```

This is working for. Try it out
