### ISSUE TITLE
[Documentation] 'shown_icon' is missing in Entity Objects table

### ISSUE THREAD

**Issue by dhzl84** [marcokreeft87/room-card#14]
The configuration options table for [Entity Objects](https://github.com/marcokreeft87/room-card#entity-objects) is missing the `show_icon` and `state_on`, `state_off` attributes.

In the provided examples they are in:
```
    - entity: binary_sensor.window
      show_icon: true
      icon:
        state_on: mdi:window-open
        state_off: mdi:window-closed
```
