### ISSUE TITLE
[Feature Request] Set a different icon if a condition is met

### ISSUE THREAD

**Issue by mihsu81** [marcokreeft87/room-card#16]
Hi @marcokreeft87,

Would it be possible to add the option to get a different icon if a certain condition is met?
I.e. Specify a tilted window icon for when the window tilt sensor is higher than 0 °.

Thanks in advance.

**Comment by marcokreeft87** [comment]
Good idea. I will look into it when I have some more time.

**Comment by nbanbury** [comment]
I managed to get icons to change based on "state" - is this something different?

```
icon:
          state_on: mdi:lamps
          state_off: mdi:lamps-outline
```

**Comment by marcokreeft87** [comment]
Yes, this is only on a on/off state for example booleans or lights. Basically all entities that only have on / off states

**Comment by marcokreeft87** [comment]
@nbanbury  check out version 1.0!

**Comment by mihsu81** [comment]
Thanks a lot. Looks great but it doesn't really help my use case.
I would need to test against another entity, not only the same entity or one of its attributes.

I.e. If a window is closed show a specific icon. If the window is open and the tilt sensor is 0, show another icon. And finally another icon if the window is open and the tilt sensor is above 0.
And here's a mock up of what I'm thinking it could look like..
```
  - entity: binary_sensor.bathroom1_window_sensor_door
    name: Window
    state_color: true
    show_state: true
    show_icon: true
    icon:
      state_off: phu:double-window-closed
      state_on: 
        conditions:
          - icon: phu:lift-in-window-open1
            condition: above
            entity: sensor.bathroom1_window_sensor_tilt
            value: 0
          - icon: phu:double-window-open
            condition: equals
            entity: sensor.bathroom1_window_sensor_tilt
            value: 0
```

**Comment by marcokreeft87** [comment]
O yeah I can add that :)

**Comment by marcokreeft87** [comment]
Check v1.1.0

**Comment by mihsu81** [comment]
It almost works for my use case. The condition is checked successfully, but I need to link it to the state condition.
If state_on and tilt = 0, display an icon, if state_on and tilt <> 0 display another icon.
Sorry for being a pain. 😄

**Comment by marcokreeft87** [comment]
@mihsu81 then you need to make template sensor I'm afraid. This will be faster then doing it in the card

**Comment by mihsu81** [comment]
No worries. I was trying to avoid creating another template sensor. 😄

**Comment by mihsu81** [comment]
I've revisited the config today and realized I can accomplish it like in the below example.

Thanks a lot @marcokreeft87 for making it possible.

```yaml
      - entity: binary_sensor.bathroom_1_window_door
        name: Window
        state_color: true
        show_state: true
        show_icon: true
        icon:
          conditions:
            - icon: phu:double-window-closed
              condition: equals
              value: 'off'
            - icon: phu:double-window-open
              condition: below
              entity: sensor.bathroom_1_window_tilt
              value: 0.9
            - icon: phu:lift-in-window-open1
              condition: above
              entity: sensor.bathroom_1_window_tilt
              value: 0.9
```
