### ISSUE TITLE
When using 'cover.set_cover_position' getting 'Failed to call service cover/set_cover_position. required key not provided @ data['position']'

### ISSUE THREAD

**Issue by mihsu81** [marcokreeft87/room-card#17]
Hi @marcokreeft87, 
When trying to use the service `cover.set_cover_position` I get the following error: `Failed to call service cover/set_cover_position. required key not provided @ data['position']` (when pressing the button).

```
  - entity: cover.master_bedroom_shutter_curtain
    name: Close Shutters
    icon: mdi:roller-shade-closed
    state_color: true
    show_state: true
    tap_action:
      action: call-service
      service: cover.set_cover_position
      data:
        position: 40
      target:
        entity_id: cover.master_bedroom_shutter_curtain
```

In a button card it works as expected.
```
type: button
tap_action:
  action: call-service
  service: cover.set_cover_position
  data:
    position: 40
  target:
    entity_id: cover.master_bedroom_shutter_curtain
entity: cover.master_bedroom_shutter_curtain
```
