### ISSUE TITLE
Adding a styles to card background  also apply to icon

### ISSUE THREAD

**Issue by Xhelliom** [marcokreeft87/room-card#192]
Hello,

For example, using this code : 

```
type: custom:room-card
entity: light.chambre_principale
title: Chambre Principale
icon: mdi:bed-queen
show_icon: true
state_color: false
tap_action:
  action: toggle
hold_action:
  action: more-info
styles:
  template: >
    if (entity.state == 'on') return 'background-image: linear-gradient(350deg,
    rgba(3,1,52,1) 0%, rgba(121,9,75,1) 41%, rgba(255,76,0,1) 100%);';
entities:
  - entity: climate.grande_chambre
    name: Chauffage
    show_icon: true
    icon:
      conditions:
        - icon: mdi:fire
          condition: equals
          value: heat
          styles:
            color: red
info_entities:
  - entity: sensor.temp_grande_chambre
```

the result look like that : 

![image](https://user-images.githubusercontent.com/18086297/226207390-4f48b144-f78e-4baf-a9d9-6a2494c2bc36.png)
