### ISSUE TITLE
Icon conditions

### ISSUE THREAD

**Issue by z4rn0x** [marcokreeft87/room-card#20]
Hello Marco
First, thank you for this card, it looks very promising!
I'm trying to customize my icons based on conditions but I can't get it to work. Is it a bug? or it is only me?
This is my code:
`type: custom:room-card
title: Garage
entities:
  - entity: sensor.rotary_encoder_1
    show_icon: true
    icon:
      conditions:
        - icon: mdi:car
          condition: below
          value: 5
        - icon: mdi:car-2-plus
          condition: above
          value: 5`
The value of my sensor is 0. I tried several sensors, different values, I'm just getting the default icon.
Thanks!

**Comment by marcokreeft87** [comment]
```

  - entity: sensor.motion_sensor_overloop_illuminance_2
    show_icon: true
    icon:
      conditions:
        - icon: mdi:car
          condition: below
          value: 5
        - icon: mdi:car-2-plus
          condition: above
          value: 5
```

I tried your config wiht a sensor of mine and this is working. Is the output of the sensor by any chance a string value in stead of an integer?
