### ISSUE TITLE
Unexpected line in the mobile view

### ISSUE THREAD

**Issue by vdbrink** [marcokreeft87/room-card#21]
Only in the mobile presentation mode there is an extra unexpected line visible. Can this also be hidden if there are no entities under that line. 
![Screenshot_20220904-111500_Home Assistant](https://user-images.githubusercontent.com/59877859/188306383-f00de2ff-1c0e-4e19-a9f9-83c9032caedf.jpg)

**Comment by marcokreeft87** [comment]
Can you share your yaml?

**Comment by vdbrink** [comment]
Here it is
```
type: entities
entities:
  - entity: sensor.x
    type: custom:room-card
    title: aquarium
    icon: mdi:fishbowl-outline
    info_entities:
      - entity: switch.x
        show_icon: true
        state_color: true
      - entity: switch.y
        show_icon: true
        state_color: true
      - entity: sensor.aquarium_temperatuur
```
