### ISSUE TITLE
Setting an entity alongside any type of tap_action is ignored.

### ISSUE THREAD

**Issue by Nurgus** [marcokreeft87/room-card#219]
**Which version of Room Card?**
1.07.20

**Describe the bug**
Setting an entity alongside any type of tap_action is ignored.

**To Reproduce**    
```
  - entity: light.clothes_dry_rail_light_3
    show_icon: true
    tap_action:
      action: toggle
    double_tap_action:
      entity: timer.clothes_dryer_timer
      action: more-info
    hold_action:
      action: more-info
      entity: timer.clothes_dryer_timer
```

**Expected behavior**
Display the more-info relating to the timer rather than just the "light" (it's actually a smart plug controlling my drying rail)
