### ISSUE TITLE
switch state not updating when turning on/off

### ISSUE THREAD

**Issue by labaland** [marcokreeft87/room-card#244]
switch and input_boolean do not change state when turning on or off
I have to refresh the page to see new state.

my card:

```
  - entities:
      - entity: input_boolean.ac_change_settings
        show_icon: true
        name: Laddare
        icon: mdi:cellphone-charging
        show_state: true
        tap_action:
          action: toggle
```
