### ISSUE TITLE
Improved Reusability

### ISSUE THREAD

**Issue by karamfil** [marcokreeft87/room-card#246]
**Is your feature request related to a problem? Please describe.**
I am looking for a way to reuse code across different room cards, I have about 10 room cards and very similar info_entities. Is there a way to reuse this, or is there something similar to [decluttering-card](https://github.com/custom-cards/decluttering-card)?

here is an example as you can see I have all the lights as info_entites since I like them compact as well as presence and temp/humidity and I have about 10 of these cards very similar. As you will see it is the same thing over and over again.

```yaml
type: custom:room-card
title: Kitchen
info_entities:
  - entity: sensor.mi_air_purifier_pro_h_temperature
  - entity: sensor.multisensor_dining_room_relative_humidity
  - entity: switch.light_switch_kitchen
    name: Light
    show_icon: true
    state_color: true
    tap_action:
      action: toggle
    double_tap_action:
      action: call-service
      service: zwave_js.ping
      service_data:
        entity_id: switch.light_switch_kitchen
  - entity: switch.light_switch_kitchen_countertop
    show_icon: true
    state_color: true
    tap_action:
      action: toggle
    double_tap_action:
      action: call-service
      service: zwave_js.ping
      service_data:
        entity_id: switch.light_switch_kitchen_countertop
  - entity: switch.light_switch_kitchen_balcony
    name: Balcony
    show_icon: true
    state_color: true
    tap_action:
      action: toggle
    double_tap_action:
      action: call-service
      service: zwave_js.ping
      service_data:
        entity_id: switch.light_switch_kitchen_balcony
  - entity: sensor.multisensor_kitchen_presence_information
    show_icon: true
    state_color: true
    icon:
      conditions:
        - icon: mdi:account-circle
          condition: equals
          value: Someone
        - icon: mdi:account-circle-outline
          condition: equals
          value: Nobody
          styles:
            color: lightgray
entities: null
view_layout:
  position: sidebar
```

if it would be possible to have something like:
```yaml
type: custom:room-card
title: Kitchen
info_entities:
  - entity: sensor.multisensor_dining_room_air_temperature
  - entity: sensor.multisensor_dining_room_relative_humidity
  - template: card-room-light-switch
  	entity: switch.light_switch_kitchen
    name: Light
  - template: card-room-light-switch
 	entity: switch.light_switch_kitchen_countertop
  - template: card-room-light-switch
 	entity: switch.light_switch_kitchen_balcony
    name: Balcony
  - template:
    name: card-room-presence
  	entity: sensor.multisensor_kitchen_presence_information
view_layout:
  position: sidebar

```

As you can see this could be compacted a lot. however, if you notice I have a double tap action with the same entity_id, and it would be great if it is possible NOT to have to define it again since it is already supplied, this would be possible with a decluttering card using [[variable-interpolation]]

**Have you tried if it is already a feature? Have you checked the wiki?**
I have tried using templates, but it does not seem to work everywhere, ex: info_entities. Also, it is not working across different room cards.

**Describe the solution you'd like**
I want to have a solid way of reusing common elements

**Describe alternatives you've considered**
I have been playing around with the decluttering-card and some other components but the room card is just soo good and compact! 🖤 

**Additional context**
Amazing card, I love it, I just can't find another way to do what I want, since anything I try is not compact and not simple, although I could do it with a decluttering-card, I did not like the result visually nor functionally.
