### ISSUE TITLE
hide_if broken with 1.2.3

### ISSUE THREAD

**Issue by pkscout** [marcokreeft87/room-card#25]
**Describe the bug**
If you try and use `hide_if` in an entity, the entire card fails to render.

**To Reproduce**
use `hide_if` in an entity

**Expected behavior**
The card should render

**Screenshots**
this code worked with 1.2.2:
```
  - entity: sensor.lanai_left_battery
    name: Lanai Left
    hide_if:
      above: 99
    icon:
      conditions:
        - condition: below
          value: 30
          styles:
            color: var(--state-icon-error-color)
```

Now it doesn't.  I have to remove every instance of `hide_if` from every entity in order for the card to render.

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Browser: any

**Additional context**

**Comment by marcokreeft87** [comment]
Yes I have made it kinda the same as the conditional icons. Should have put it in the release notes more specifically. Check the documentation for hiding. If you can't get it to work let me know

**Comment by pkscout** [comment]
That works.  Thanks.  Sometimes I just need one good example.  I tried a bunch of different variations on the icon condition structure, but not that one.

**Comment by marcokreeft87** [comment]
Haha yeah this one is on me. Needed to put an example in the docs. It might change in the future to be exactly the same as icons. But hopefully I won't forget to put it in the release notes then haha

**Comment by marcokreeft87** [comment]
@pkscout Already did it to make it less of a surprise for you in the future :) all you need to change is 

```
  - entity: sensor.lanai_left_battery
    name: Lanai Left
    hide_if:
      **conditions:**
        - condition: above
          value: 99
    icon:
      conditions:
        - condition: below
          value: 30
          styles:
            color: var(--state-icon-error-color)
```
