### ISSUE TITLE
Template as entity name

### ISSUE THREAD

**Issue by kaizer666** [marcokreeft87/room-card#271]
I have input_text with value equals user person 

```
{{ states("input_text.n100_last_username") }} {# person.maksim #}
```

How to set entity name in room-card by use this template?

This example does not work: 
```
type: custom:room-card
title: Title
tap_action:
  action: navigate
  navigation_path: /lovelace-home/1
rows:
  - type: entities
    entities:
      - show_icon: true
        entity: '{{ states("input_text.n100_last_username") }}'
```

This example works: 
```
type: custom:room-card
title: Title
tap_action:
  action: navigate
  navigation_path: /lovelace-home/1
rows:
  - type: entities
    entities:
      - show_icon: true
        entity: person.maksim
```
