### ISSUE TITLE
Room-cards with Entities of type "media-player." are not displaying after update to v. 1.08.00

### ISSUE THREAD

**Issue by BrettEBowman** [marcokreeft87/room-card#279]
**Which version of Room Card?**
1.08.00

**Describe the bug**
I just updated to version 1.08.00 and now several of my room-cards are not displaying. Through trial and error, I figured out that the ones not displaying have media-player.xxxx entries in their main entities: list. If I remove all of the media-player entities in the list, then the room card displays.

**To Reproduce**
See above.

**Expected behavior**
The room-cards which were displaying properly before updating to 1.08.00 would still display properly.

**Screenshots**
With media-player entities, this card doesn't display:
![Screenshot 2023-10-14 213510](https://github.com/marcokreeft87/room-card/assets/17341309/9ddf6239-7c27-4397-aeb6-5283962330d7)

When the media-player entities are removed, the card does display:
![Screenshot 2023-10-14 213607](https://github.com/marcokreeft87/room-card/assets/17341309/b60b1b6f-a9a8-4335-807d-0233678fe2ba)

**Additional context**

**Comment by BrettEBowman** [comment]
It looks like it is not specifically related to the media-player entity type.

I was able to get the first entity to display by moving the "icon:" line in the "conditions:" section to the first position (after the "-"). From:
```
    icon:
      conditions:
        - condition: equals
          attribute: source
          value: KODI on RPi
          icon: phu:tivo
```
To:
```
    icon:
      conditions:
        - icon: phu:tivo
          condition: equals
          attribute: source
          value: KODI on RPi
```

However, making the same change in the 2nd one doesn't make it display. 
To:
```
  - entity: media_player.tivo_stream_4k_2
    name: TiVo
    show_icon: true
    icon:
      conditions:
        - icon: phu:prime-video
          condition: equals
          attribute: app_name
          value: com.amazon.amazonvideo.livingroom
        - icon: phu:youtube
          condition: equals
          attribute: app_name
          value: com.google.android.youtube.tv
        - icon: phu:netflix
          condition: equals
          attribute: app_name
          value: com.netflix.ninja
        - icon: phu:plex
          condition: equals
          attribute: app_name
          value: com.emveepee.uidroid
```
