### ISSUE TITLE
hide_if doesn't hide the entity after v1.2.5 if the value is a list

### ISSUE THREAD

**Issue by mihsu81** [marcokreeft87/room-card#29]
**Describe the bug**
After the upgrade from v1.2.2 to v1.2.5 _hide_if_ doesn't hide the entity if the value is a list.

**To Reproduce**
Steps to reproduce the behaviour:
Use a list of values to compare against.
```yaml
  - entity: sensor.d5448f4584034770844ddab4e6873e51_100_1_room_presence
    name: Mihai
    state_color: true
    show_state: true
    show_icon: true
    hide_if:
      conditions:
        - condition: equals
          value:
            - not_home
            - Lobby
            - Living Room
            - Master Bedroom
            - Sonia's Bedroom
```

**Expected behaviour**
Hide the entity if the value is matched against one of the values
Used to work fine in v1.2.2 with the previous implementation of _hide_if_.
```yaml
  - entity: sensor.d5448f4584034770844ddab4e6873e51_100_1_room_presence
    name: Mihai
    state_color: true
    show_state: true
    show_icon: true
    hide_if:
      value:
        - not_home
        - Lobby
        - Living Room
        - Master Bedroom
        - Sonia's Bedroom
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - Version any

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Browser: any
 - Version: any

**Additional context**

**Comment by marcokreeft87** [comment]
Hey @mihsu81. The config for hiding changed: https://github.com/marcokreeft87/room-card/wiki/Configuration#hiding.
So yours would be:

```yaml
  - entity: sensor.d5448f4584034770844ddab4e6873e51_100_1_room_presence
    name: Mihai
    state_color: true
    show_state: true
    show_icon: true
    hide_if:
     conditions:
      - condition: equal
        value: not_home
      - condition: equal
        value: Lobby
      - condition: equal
        value: Living Room
      - condition: equal
        value: Master Bedroom
      - condition: equal
        value: Sonia's Bedroom
```

I changed this so all conditional entities would work the same in the card
