### ISSUE TITLE
Frontend memory leak when combined with card-mod

### ISSUE THREAD

**Issue by qupada** [marcokreeft87/room-card#291]
**Which version of Room Card?**
1.08.02

**Describe the bug**
Combing card-mod and room-card creates a javascript memory leak that crashes a HA tab within a few minutes (at >2GB of memory usage).

**To Reproduce**
Install [card-mod](https://github.com/thomasloven/lovelace-card-mod) from HACS.
Create the dashboard listed at the bottom (has one room-card, one child glance card with one entity), or full dashboard with 9 from linked gist.

**Expected behavior**
Normal execution.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux (KDE Neon 5.27) and Windows (10)
 - Browser Firefox (119, 120 beta) and Chrome (119)

**Smartphone (please complete the following information):**
 - Device: Sony Xperia 1ii
 - OS: Android 12
 - Browser HA App
 - Version 2023.11.1-full

**Additional context**

* Unbounded Javascript memory growth, starting (according to Chrome developer tools) around 30MB on a fresh page load, peaking at around 2.4GB before the tab hangs or crashes outright. Memory use consistently increases by around 0.8 - 1.2MB/s with around 15 cards having the above configuration, and seems to scale relatively linearly (60kB/s with 1 card).
* Almost all interaction with the dashboard is unusuably laggy after a tab has been open for more than around a minute (around 0.5GB of memory use); single clicks end up treated as long click, some actions run but GUI state does not update for 5-10 seconds, and scrolling is laggy and jumps around randomly.
* Android app is almost entirely unusable after around 1-2 interactions with the dashboard. Requires a full force close of the app to re-gain control.

NOTE: most of this description copied from https://github.com/thomasloven/lovelace-card-mod/issues/312

I thought this might be a repeat of https://github.com/marcokreeft87/room-card/issues/290 but I can reproduce the behaviour with a dashboard containing only a single room-card with a single glance card nested, so it's not triggered only by large dashboards and/or other custom cards (my only other custom card is a single [simple-thermostat](https://github.com/nervetattoo/simple-thermostat)).

I have pasted the full ~600 line YAML dashboard here: https://gist.github.com/qupada/5ab42d4d3aa753e65fb4f221a191d127 - this was working up until 2-3 weeks ago without issue.

The minimal test case that triggers the bug is reproduced below:

**YAML**
```yaml
  - title: test
    path: test
    badges: []
    cards:
      - type: custom:room-card
        title: Office
        cards:
          - type: glance
            show_name: true
            show_icon: true
            show_state: false
            state_color: true
            card_mod:
              style: |
                ha-card {
                  border: none;
                  padding: 0 !important;
                }
            entities:
              - entity: light.office_ceiling
                name: Ceiling
                tap_action:
                  action: toggle
```
