### ISSUE TITLE
Wrong Icons shown for Motion devices in Info Entities 

### ISSUE THREAD

**Issue by jane-t** [marcokreeft87/room-card#316]
**Which version of Room Card?**

1.08.03
**Describe the bug**
Since upgrading all my Motion Sensors on the room card in the Info area are showing with a default icon not the motion one.   They do appear correctly on a home assistant standard entity card.

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="555" alt="image" src="https://github.com/marcokreeft87/room-card/assets/920792/5baf3f69-b8fc-4fce-a7ef-713705c3b40d">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS Macbook Pro and others
 - Browser [e.g. chrome, safari] Arc

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Android Phone and Tablet
 - Browser [e.g. stock browser, safari] Chrome and Android Home Assistant App

**Additional context**

I suspect this is related to the new logic for Icons introduced in 2024.2,  all my motion devices are either ZHA connected or ESPHome

**YAML**
`
type: custom:room-card
title: Kitchen
icon: mdi:chef-hat
show_icon: true
entity: binary_sensor.kitchen_occupied
tap_action:
  action: navigate
  navigation_path: /lovelace-yaml-rooms/kitchen
state_color: true
entities:
  - entity: light.kitchen_lights
    name: Main
    tap_action:
      action: toggle
  - entity: light.utility_light
    name: Utility
    tap_action:
      action: toggle
  - media_player.kitchen

  - entity: climate.zone_4_kitchen
    tap_action:
        action: more-info
    state_color: true
    name: Heating
info_entities:
  - entity: binary_sensor.kitchen_ep1_occupancy
    show_icon: true
    state_color: true
  - entity: sensor.no_4_temp
    tap_action:
      action: more-info
      entity: climate.zone_4_kitchen
      
  - entity: sensor.no_4_target
    tap_action:
      action: more-info
`

**Comment by marcokreeft87** [comment]
You are posting the yaml of another room as the screenshot. Can you post the yaml of the same room plz?

**Comment by jane-t** [comment]
They all have the same problem.

**Comment by marcokreeft87** [comment]
Maybe it's me but you have 7 entities in the yaml and 4 in the picture.

But besides that, could it be that the device class isn't motion? 
Because mine are working fine

**Comment by jane-t** [comment]
`type: custom:room-card
title: Kitchen
icon: mdi:chef-hat
show_icon: true
entity: binary_sensor.kitchen_occupied
tap_action:
  action: navigate
  navigation_path: /lovelace-yaml-rooms/kitchen
state_color: true
entities:
  - entity: light.kitchen_lights
    name: Main
    tap_action:
      action: toggle
  - entity: light.utility_light
    name: Utility
    tap_action:
      action: toggle
  - media_player.kitchen

  - entity: climate.zone_4_kitchen
    tap_action:
        action: more-info
    state_color: true
    name: Heating
info_entities:
  - entity: binary_sensor.kitchen_ep1_occupancy
    show_icon: true
    state_color: true
  - entity: sensor.no_4_temp
    tap_action:
      action: more-info
      entity: climate.zone_4_kitchen
      
  - entity: sensor.no_4_target
    tap_action:
      action: more-info

`

**Comment by marcokreeft87** [comment]
Only difference in yaml I can find is that I don't have the state_color: true.

Can you try without?

**Comment by jane-t** [comment]
<img width="606" alt="image" src="https://github.com/marcokreeft87/room-card/assets/920792/0b0979ca-f993-4e60-b4c1-49e904b992c5">
More info for Occupancy icon for Kitchen

**Comment by jane-t** [comment]
Sorry removing the state colour does not fix it.
I checked and the device class for the Kitchen EP1 Occupancy is 
device_class: occupancy
friendly_name: Kitchen ep1 Occupancy

**Comment by marcokreeft87** [comment]
That's what I thought.
The icon you see is the default occupation icon.

Guess it's your configuration, because you are the first reporting this and mine is working correctly.

I can't help you I'm afraid.

**Comment by jane-t** [comment]
Ok,  I just don't understand why the icon on the Room card is different to that on the More info pop up.

**Comment by marcokreeft87** [comment]
I've had that issue before. Did you set the icon in a yaml file configuration?

**Comment by jane-t** [comment]
No,  they are just the default ones from the class.  Obviously I can set them in the room card or the entity but I have not and just let the default ones appear.   Which is why I suspected something with the icon changes being implemented in 2024.2

**Comment by jane-t** [comment]
Ok, as an experiment I manually set the Kitchen sensor to mdi:home on the entity and the room card displayed correctly.  So it is probably something to do with the inheritance of the new icon formats.

**Comment by marcokreeft87** [comment]
> No,  they are just the default ones from the class.  Obviously I can set them in the room card or the entity but I have not and just let the default ones appear.   Which is why I suspected something with the icon changes being implemented in 2024.2
> 

Well I know for a fact that the default icon for occupancy isn't a house icon

**Comment by marcokreeft87** [comment]
> I can work around the problem by manually setting the icons so if no one else  is getting the problem it must be something odd. Sorry to have bothered you.
> 

That's ok. Wish I could have helped.

**Comment by geoffmellis** [comment]
Just updated HA and having the exact issue as above.

**Comment by jane-t** [comment]
<img width="521" alt="image" src="https://github.com/marcokreeft87/room-card/assets/920792/a8aba0c4-2d97-43e9-a5d2-0e28d879a0bd">

I have been experimenting some more. I created a new dashboard

The above shows the output.
```
views:
  - title: Home
    cards:
      - type: custom:room-card
        title: Bedroom
        icon: mdi:bed
        show_icon: true
        entity: binary_sensor.bedroom_occupied
        tap_action:
          action: navigate
          navigation_path: /lovelace-yaml-rooms/bedroom
        state_color: true
        entities:
          - entity: light.bedroom_1_main_light
            name: Main
          - entity: light.tas_plug_2
            name: Cupboard
            tap_action:
              action: toggle
          - entity: light.ensuite_light
            name: Ensuite
            state_color: true
            show_icon: true
            tap_action:
              action: toggle
          - entity: fan.ensuite_light_fan
            name: Extractor
            state_color: true
            show_icon: true
            tap_action:
              action: toggle
          - entity: switch.tp2_tv
            state_color: true
            icon: mdi:television
            show_icon: true
            name: TV
            tap_action:
              action: toggle
          - entity: media_player.fire_tv_192_168_50_105
            hide_if:
              conditions:
                - condition: equals
                  entity: switch.tp2_tv
                  value: 'off'
          - entity: climate.zone_5_bedroom_1
            tap_action:
              action: more-info
            state_color: true
            name: Heating
        info_entities:
          - entity: binary_sensor.bedroom_motion
            show_icon: true
            state_color: true
          - entity: binary_sensor.ensuite_sensor_occupancy
            show_icon: true
            state_color: true
          - sensor.no_5_temp
          - sensor.no_5_target
      - type: entities
        entities:
          - entity: binary_sensor.ensuite_sensor_motion
          - entity: binary_sensor.ensuite_sensor_occupancy
          - entity: fan.ensuite_light_fan
          - entity: binary_sensor.bedroom_motion
          - entity: binary_sensor.lumi_lumi_sensor_motion_aq2_occupancy

```
