### ISSUE TITLE
State ignores sensor‘s device_class

### ISSUE THREAD

**Issue by snowy-18** [marcokreeft87/room-card#337]
**Which version of Room Card?**
1.08.04 but has always been like this

**Describe the bug**
The device_class of a sensor is being ignored  when showing the state of a sensor on the room card. In my example, a binary flood sensor has the state "dry" in the general Home Assistant UI, but on the Room Card it is shown as "off". That's technically correct, but ignored the global settings applied to the entity.

**To Reproduce**
Take any sensor and modify its device_class in the entity's customize section: https://www.home-assistant.io/integrations/sensor/

**Expected behavior**
The state shown on the room card should be the same as in the entity's settings.

**Screenshots**
<img width="736" alt="image" src="https://github.com/marcokreeft87/room-card/assets/101481932/953132ed-4d6f-4226-a290-4fda19d414de">

**Desktop (please complete the following information):**
Mac, Windows, Web

**Smartphone (please complete the following information):**
iOS

**Additional context**
Maybe related to #249? The state on the room card remains "off", even if I change the UI to another language than English.

**YAML**
```
type: custom:room-card
title: Waschküche
icon: mdi:washing-machine
show_icon: true
state_color: true
entity: sensor.waschkuche_waschmaschine_power
info_entities:
  - entity: sensor.waschkuche_wassersensor_temperature
    format: precision1
rows:
  - entities:
      - entity: sensor.washing_machine_current_state_translated
        name: Waschmaschine
        show_state: true
      - entity: sensor.dryer_current_state_translated
        name: Trockner
        show_state: true
      - entity: binary_sensor.waschkuche_wassersensor_flood
        name: Wasser
        show_state: true
```

**Comment by marcokreeft87** [comment]
What is the state in the developer tools of HA?

**Comment by snowy-18** [comment]
![image](https://github.com/marcokreeft87/room-card/assets/101481932/1901c7e1-5102-41a3-9b46-f96914fbb4e7)

The state is "off", as displayed on the room card. According to the HA documentation, the [Device Class](https://www.home-assistant.io/integrations/sensor/#device-class) influences how the entity is represented in the dashboard.

**Comment by marcokreeft87** [comment]
Thats excepted behavior. You need to pass which attribute you want to show if you dont want to see the state there

``attribute: ``` in config

**Comment by snowy-18** [comment]
Thanks for your help. Btw, great card!! Really the only one that I'm using on my main dashboard and probably the main reason why the whole family startet using HA 👍 

So I tried adding: 
`attribute: device_class`

As I'd expect, then the label reads "moisture", and not "dry":
![image](https://github.com/marcokreeft87/room-card/assets/101481932/7d70a267-9b9e-4943-a11c-5cf78e60f021)

I feel like I'm not getting how to use the attribute here? 

In a normal entity card, the state is "dry" and not "off", just as it is configured in the entity's settings:
![image](https://github.com/marcokreeft87/room-card/assets/101481932/f2c19e08-8ba4-48ae-a111-3dabf4ba4c81)

**Comment by marcokreeft87** [comment]
You need to use the flood entity apparently. State should give the wanted result with that entity

Take a look at the entities in developer tools. There you can see all the attributes

**Comment by snowy-18** [comment]
Gave this another try on a fresh dashboard, where I added the same entity on different cards. The stock HA `Entity`, `Entities` and `Glance` cards, as well as custom `Room`, `Bubble` and `Mushroom` cards.

```
  - title: Test
    path: test
    cards:
      - type: custom:room-card
        title: Room-card
        rows:
          - entities:
              - entity: binary_sensor.waschkuche_wassersensor_flood
                show_state: true
      - type: entity
        entity: binary_sensor.waschkuche_wassersensor_flood
      - type: entities
        entities:
          - entity: binary_sensor.waschkuche_wassersensor_flood
      - type: glance
        show_name: true
        show_icon: true
        show_state: true
        entities:
          - entity: binary_sensor.waschkuche_wassersensor_flood
      - type: custom:mushroom-entity-card
        entity: binary_sensor.waschkuche_wassersensor_flood
      - type: custom:bubble-card
        card_type: button
        button_type: state
        entity: binary_sensor.waschkuche_wassersensor_flood
```

The `room-card` is the only one which displays the state as `off` instead of `dry`:
![image](https://github.com/marcokreeft87/room-card/assets/101481932/f9c7492d-7985-4e0c-acf0-3be94719163e)

Here are the entity's `state` and `attributes` in the developer tools:
![image](https://github.com/marcokreeft87/room-card/assets/101481932/ae6bc660-5b11-4118-8a9d-d1bc86278e8c)

So yes, technically the state is `off` and not `dry`, but the `entity` is configured as the `device_class: moisture` / **Show as: Moisture**.
![image](https://github.com/marcokreeft87/room-card/assets/101481932/1bc9d4d0-e077-4b9b-8354-0437a151b78c)

If I change the `device_class` to anything else, e.g. **Show as: Smoke**, all cards on the dashboard above will show the state as `Clear`, or **Show as: Safety**, all cards on the dashboard above will show the state as `Save` ...
... but the `Room-card` will remain as `Off`. 

I might be wrong but don't think this is an issue with the attribute of the entity, rather how the `Room-card` handles the `device_class`.
Thoughts?
