### ISSUE TITLE
Entity Objects with just an icon are not rendered

### ISSUE THREAD

**Issue by felixmxr** [marcokreeft87/room-card#338]
**Which version of Room Card?**
v1.08.04

**Describe the bug**
Entity Objects created with just an "icon" and no "entity" or "attribute" are not rendered

**To Reproduce**
create an entity object under "entitites" as follows
- icon: mdi:pause
  show_icon: true
  name: pause TV
  tap_action: //define your action here

**Expected behavior**
According to the documentation (https://github.com/marcokreeft87/room-card/wiki/Configuration#entity-objects), I would expect this object to be rendered

**Additional context**
if any valid "entity" is added to the object it works

**YAML**
```
type: custom:room-card
entity: switch.tv
name: test
icon: mdi:remote-tv
show_icon: true
entities:
  - entity: switch.am4_switch_0
  - icon: mdi:pause
    show_icon: true
    name: pause
    tap_action:
          action: call-service
          service: webostv.button
          service_data:
            entity_id: media_player.lg_webos_tv_oled55c97la
            button: PLAY
```
