### ISSUE TITLE
Templates Issue: TypeError: Cannot read properties of null (reading 'state_on')

### ISSUE THREAD

**Issue by lennon101** [marcokreeft87/room-card#344]
**Which version of Room Card?**

`1.08.04`

**Describe the bug**

When trying to use the templates as described in the wiki, an error appears in the preview window: 

**To Reproduce**
n/a

**Expected behavior**

After adding the template code as provided by the wiki, I would expect the icon to turn yellow when the entities state is 'on' 

**Screenshots**

<img width="1006" alt="Screenshot 2024-08-30 at 7 03 15 AM" src="https://github.com/user-attachments/assets/a45a27df-7e29-4ea2-a09f-88d4ed450a93">

**Desktop (please complete the following information):**
 - OS: macOS 14.5 (23F79)
 - Browser Chrome 
 - Version 127.0.6533.120 (Official Build) (arm64)

**Additional context**

Without templating, the icon turns yellow without any issues (just using the normal styles method per entity). 

**YAML**

```
type: custom:room-card
title: BATHROOM
entity: light.bathroom_lights_group
show_state: false
tap_action:
  action: navigate
  navigation_path: /dashboard-rooms/bathroom
templates:
  - name: test_template
    template:
      show_icon: true
      state_color: true
      icon:
      template:
        styles: >
          if (entity.state == 'on') return 'color: yellow';  

entities:
  - entity: light.shellyswitch25_c8c9a3759e8b_channel_1
    name: Ceiling
    template: test_template
```
