### ISSUE TITLE
Styles and templating does not work for light entities 

### ISSUE THREAD

**Issue by lennon101** [marcokreeft87/room-card#346]
**Which version of Room Card?**

`1.08.04`

**Describe the bug**

Using the styling (as outlined in the wiki) I can change the color of an enitity that is anything is but a light, but a light will not obey the same code.

**Screenshots**

<img width="1009" alt="Screenshot 2024-08-30 at 7 42 19 AM" src="https://github.com/user-attachments/assets/f5062234-00bc-4a4d-beae-0bf89e8dccac">

**YAML**

```
type: custom:room-card
title: Living Room
entity: light.movie_lamp
show_state: false
entities:
  - entity: light.movie_lamp
    name: Movie Lamp
    tap_action:
      action: toggle
    show_icon: true
    show_state: true
    icon:
      template:
        styles: |
          if (entity.state == 'on') return 'color: yellow';  
  - entity: input_boolean.sleep_mode
    name: Sleep Mode
    tap_action:
      action: toggle
    show_icon: true
    show_state: true
    icon:
      template:
        styles: |
          if (entity.state == 'on') return 'color: yellow';  

```
