### ISSUE TITLE
Icon color

### ISSUE THREAD

**Issue by carlywarly** [marcokreeft87/room-card#42]
Would it bo possible to change to color of a highlighted icon? For example, color: rgb(93, 173, 226), this would make it easier to match current color schemes? 

```yaml
type: custom:room-card
title: Office
entity: input_boolean.inoffice
state_color: true
color: rgb(93, 173, 226)
icon:
  conditions:
    - icon: null
      condition: equals
      value: 'off'
    - icon: mdi:door-closed
      condition: equals
      value: 'on'
entities:
  - entity: switch.officelight
    name: Light
    state_color: true
    color: rgb(93, 173, 226)
    icon: phu:ceiling-round
    tap_action:
      action: toggle
```

Again, many thanks,
Carl

**Comment by marcokreeft87** [comment]
The icon conditions have a styles property. You can use that. But maybe You have to set state_color to false then

**Comment by marcokreeft87** [comment]
Btw, next time, create a discussion for questions plz. It's no problem for now 😀

**Comment by carlywarly** [comment]
Again many thanks, was banging my head, ended up with:

```yaml
type: custom:room-card
title: Den
entity: input_boolean.inoffice
show_icon: true
icon:
  conditions:
    - icon: mdi:door-open
      condition: equals
      value: off
      styles:
        color: rgb(93, 173, 226)
    - icon: mdi:door-closed
      condition: equals
      value: off
entities:
  - entity: switch.officelight
    name: Light
    icon:
      conditions:
        - icon: phu:ceiling-round
          condition: equals
          value: on
          styles:
            color: rgb(93, 173, 226)
        - icon: phu:ceiling-round
          condition: equals
          value: off
    tap_action:
      action: toggle
```

again thanks :)
Carl
