### ISSUE TITLE
horizontal scrolling 

### ISSUE THREAD

**Issue by Polimac** [marcokreeft87/room-card#53]
hi again me :)

i got horizontal scrolling issue in app on mobile , when your card is in dashboard
i am able to move horizontally screen

![2022-09-18 14 13 51](https://user-images.githubusercontent.com/16742142/190901551-c0111c41-d5e4-4486-8bd7-74ae0a94a3c0.jpg)

code

type: custom:room-card
title: Livingroom
rows:
  - entities:
      - entity: light.livingroom_ceiling
        name: Livingroom ceiling
        icon: mdi:ceiling-light
        tap_action:
          action: toggle
      - entity: light.0x00124b0022727206
        name: Livingroom Ambient
        icon: mdi:led-strip
        tap_action:
          action: more-info
      - entity: light.livingroomspotlight
        name: Livingroom Spot
        icon: mdi:track-light
        tap_action:
          action: toggle
      - entity: light.wc_pathway
        name: WC Pathway
        icon: mdi:lightbulb
        tap_action:
          action: toggle
  - entities:
      - entity: light.kitchen_spot_1
        name: Kitchen Spot 1
        icon: mdi:ceiling-light-multiple
        tap_action:
          action: toggle
      - entity: light.kitchen_spot_2
        name: Kitchen Spot 2
        icon: mdi:ceiling-light-multiple
        tap_action:
          action: toggle
      - entity: light.kitchen_led
        name: Kitchen Led
        icon: mdi:led-strip
        tap_action:
          action: toggle
  - entities:
      - entity: light.wc_ceiling
        name: WC Ceiling
        icon: mdi:ceiling-light-multiple
        tap_action:
          action: toggle
      - entity: light.wc_mirror
        name: WC Mirror light
        icon: mdi:led-strip-variant
        tap_action:
          action: toggle
      - entity: switch.0x5c0272fffe1cae01_l1
        name: WC Ventilation
        icon: mdi:fan
        state_color: true
        tap_action:
          action: toggle
  - entities:
      - entity: light.doorwaygrouplight
        name: Doorway
        icon: mdi:ceiling-light-multiple
        tap_action:
          action: toggle
      - entity: light.hallway
        name: Hallway
        icon: mdi:ceiling-light-multiple
        tap_action:
          action: toggle
  - entities:
      - entity: cover.0xa4c13862a3c38fec
        name: Shade
        tap_action:
          action: toggle
        state_color: true
      - entity: fan.0xb4e3f9fffe2b20e6
        name: Airpurifier
        icon: mdi:air-filter
        tap_action:
          action: more-info
        state_color: true
info_entities:
  - entity: sensor.livingroomsensor_temperature
  - entity: sensor.livingroomsensor_humidity
  - entity: sensor.0xb4e3f9fffe2b20e6_pm25

**Comment by marcokreeft87** [comment]
I think you have too many entities on one row

**Comment by marcokreeft87** [comment]
Reading back my comment didnt make sense.  I think there is something that is waayy to wide for this view. Dont think this is because of the room card tho. Could be that it only happens when the card is being added. But everything in the card is nice and neat between the borders of the card in your screenshot. Isnt there something lower that is wider than the view?

**Comment by marcokreeft87** [comment]
@mihsu81 can you make the names shorter? See if that helps

**Comment by mihsu81** [comment]
@marcokreeft87 Doesn't seem to help. 
I've also removed the additional styling from the card.
![Screenshot_2022-09-20-08-14-59-53_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/40715497/191173323-d09ba87e-41c2-4951-afeb-1f9305a05f93.jpg)

**Comment by marcokreeft87** [comment]
Hmm and make rows of 5 entities max?

**Comment by marcokreeft87** [comment]
And what's that weird bar to the right?

**Comment by marcokreeft87** [comment]
Idk guys, I cant reproduce:
![image](https://user-images.githubusercontent.com/10223677/191252642-910b748e-64d7-44c2-ba3b-1a8612d066d0.png)
![image](https://user-images.githubusercontent.com/10223677/191252734-0db620cb-2154-4e8f-93f9-a237c9f89bb8.png)

```
type: custom:room-card
title: test
entity: light.mancave_lampen
icon: mdi:floor-lamp-outline
show_icon: true
tap_action:
  action: toggle
rows:
  - entities:
      - entity: light.mancave_lamp
        name: Plafond dfdfdfd fdfdfdsfdsfds
        tap_action:
          action: toggle
        hold_action:
          action: more-info
      - entity: light.mancave_lamp
        name: Plafond dfdfdfd fdfdfdsfdsfds
      - entity: light.mancave_lamp
        name: Plafond dfdfdfd fdfdfdsfdsfds
      - entity: light.mancave_lamp
        name: Plafond
      - entity: light.mancave_lamp
        name: Plafond
      - entity: light.mancave_lamp
        name: Plafond
      - entity: light.mancave_lamp
        name: Plafond
      - entity: light.mancave_lamp
        name: Plafond
      - entity: light.mancave_lamp
        name: Plafond
      - entity: light.mancave_lamp
        name: Plafond
  - entities:
      - entity: light.mancave_lamp
        name: Plafond
        tap_action:
          action: toggle
        hold_action:
          action: more-info

```

**Comment by Polimac** [comment]
i think it is related to info_entities

**Comment by marcokreeft87** [comment]
> i think it is related to info_entities

Can you reproduce with only info_entities?

**Comment by mihsu81** [comment]
I've reduced the number of entities per row to 5 and the issue persists. 
The bar to the right is created by the HA app when  the size is higher. It's the same color as the upper frame.
![Screenshot_2022-09-20-19-17-20-09_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/40715497/191311787-1a551697-b284-4579-a9e6-6fb77167a777.jpg)

**Comment by marcokreeft87** [comment]
Hmm, can you try a different theme?

**Comment by mihsu81** [comment]
The issue appears with the default theme as well.
The theme is https://github.com/tgcowell/waves.
![Screenshot_2022-09-20-19-56-17-78_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/40715497/191319280-3d97a664-1089-49d0-9063-ba2b346eaff0.jpg)

**Comment by marcokreeft87** [comment]
Super weird. Share the yaml of that dashboard plz and I will try to reproduce. But since I see so many without this problem I'm inclined to say it's something in your settings. But let's see

**Comment by mihsu81** [comment]
```yaml
title: Home Dashboard
views:
  - title: Test room card
    path: test-room-card
    badges: []
    cards:
      - type: custom:room-card
        title: Kitchen
        entity: binary_sensor.area_kitchen
        icon: hue:room-kitchen
        state_color: true
        show_state: true
        show_icon: true
        column: false
        rows:
          - entities:
              - entity: light.kitchen_light
                name: Light
                icon: hue:pendant-cher
                state_color: true
                show_state: true
                show_icon: true
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
```
It does make sense that it's some card we have installed, but who knows which.
Here's a list of Frontend integrations I have installed which might be the cause, since thy deal with styling.
Stack In Card
Purifier Card
Vacuum Card
Config Template Card
Simple Weather Card
Vertical Slider Cover Card
KNX User Forum Icon Set
Simple Thermostat
badge-card
card-mod
BHA Icon Pack
bignumber-card
Custom brand icons
Vertical Stack In Card
mini-graph-card
Xiaomi Vacuum Map Card
Bar Card
card-tools
slider-entity-row
Mini Media Player
mini climate card
button-card
auto-entities
Hass Hue Icons
Alarmo Card
Waves
Body Miscale Card
Config Editor Card
Better Thermostat UI
history-explorer-card
Plotly Graph Card
Thermal Comfort Icons
Only Lock Lock Row
Flower Card
Nordic Theme
custom-icons
TV Remote Card (with touchpad and haptic feedback)
My Cards Bundle
Swiss Army Knife custom card
Valetudo Map Card
Room Card
