### ISSUE TITLE
Main entity still required

### ISSUE THREAD

**Issue by usernein** [marcokreeft87/room-card#56]
**Describe the bug**
I read in the release notes that a main entity is not required anymore, but i'm still getting an error when i don't set "entity"
I'm using v1.4.1 

**Screenshots**
<img width="468" alt="Captura de Tela 2022-09-21 às 14 48 59" src="https://user-images.githubusercontent.com/29507335/191575343-87d73408-b45e-471d-90ef-7b43e5871f32.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 105

This is the yaml:
```yaml
type: custom:room-card
title: Quarto
entities:
  - entity: light.quarto
    state_color: true
    show_name: false
  - entity: media_player.tv
    show_name: false
  - entity: switch.velocidade_1
    icon: mdi:fan-speed-1
    show_icon: true
    show_name: false
  - entity: switch.velocidade_2
    icon: mdi:fan-speed-2
    show_icon: true
    show_name: false
  - entity: switch.velocidade_3
    icon: mdi:fan-speed-3
    show_icon: true
    show_name: false
```

**Comment by marcokreeft87** [comment]
Good thing is, I can confirm that 1.4.1 doesnt have the issue. But its not ready for release :(

**Comment by thewolfman56** [comment]
Mine shows 1.4.1

![image](https://user-images.githubusercontent.com/71470070/191584932-a8874dcd-b617-4976-b743-b80be01ae34a.png)

**Comment by marcokreeft87** [comment]
In Developer tools console I meant

**Comment by thewolfman56** [comment]
My apologies.  I have never used the developer tools to view the download version.  I could look at it for you, but would need to know how.

**Comment by marcokreeft87** [comment]
> 

Press F12 and it should be on the tab " console ". Refresh the page and you will see it

**Comment by marcokreeft87** [comment]
Try version 1.5.0 and see if it works

**Comment by markwoodward86** [comment]
Came here to report the same issue. I confirm 1.5.0 resolves the bug

**Comment by markwoodward86** [comment]
although it does look like 'title' is not being picked up any longer
![Mobile_View_–_Home_Assistant](https://user-images.githubusercontent.com/47867906/191600703-d55856b8-b2e4-44da-a545-4eb67b1c3eb8.jpg)

**Comment by thewolfman56** [comment]
> > 
> 
> Press F12 and it should be on the tab " console ". Refresh the page and you will see it

My apologies.  I was looking in the Home Assistant Developer Tools.  On the Chrome console, my version is 1.4.0 even though HACS shows I downloaded 1.4.1.

I'll try to download 1.5.0

**Comment by marcokreeft87** [comment]
> although it does look like 'title' is not being picked up any longer
> 
> ![Mobile_View_–_Home_Assistant](https://user-images.githubusercontent.com/47867906/191601333-5b70aba6-8241-4541-890e-ff45d056fc6e.jpg)
> 

Could be a cache issue. Do you have a way to clear it? Otherwise I will look at it tomorrow.

**Comment by marcokreeft87** [comment]
> > > 
> > 
> > Press F12 and it should be on the tab " console ". Refresh the page and you will see it
> 
> My apologies.  I was looking in the Home Assistant Developer Tools.  On the Chrome console, my version is 1.4.0 even though HACS shows I downloaded 1.4.1.
> 
> I'll try to download 1.5.0

Yes I had the same issue. HA is super weird with caching unfortunately

**Comment by marcokreeft87** [comment]
@thewolfman56 check out v1.5.1 I think I found the issue

**Comment by thewolfman56** [comment]
> > although it does look like 'title' is not being picked up any longer
> > ![Mobile_View_–_Home_Assistant](https://user-images.githubusercontent.com/47867906/191601333-5b70aba6-8241-4541-890e-ff45d056fc6e.jpg)
> 
> Can you try 1.5.1?

Seems to be working as it had previously.  Title shows up for me.

```
type: custom:room-card
title: Pool
hide_title: false
icon: mdi:pool
show_icon: true
info_entities:
  - entity: sensor.water_sensor_1
    show_icon: false
  - entity: sensor.water_sensor_1
    show_icon: true
    icon: mdi:pool-thermometer
  - entity: binary_sensor.heat_pump
    name: Heat Pump
    show_name: true
rows:
  - entities:
      - entity: light.pool_lights_no
        name: Pool Light Group
        tap_action:
          action: toggle
        hold_action:
          action: more-info
      - entity: light.baja_light
        tap_action:
          action: toggle
      - entity: light.pool_lights
        tap_action:
          action: toggle
      - entity: light.grotto_light
        tap action: toggle
      - entity: light.waterfall_light
        name: Waterfall Lights
        tap_action:
          action: toggle
  - entities:
      - entity: switch.waterfall_scene_switch
        name: Waterfall
        icon: mdi:pool
        show_icon: true
      - entity: switch.waterfall_scene_switch
        name: Waterslide
        icon: mdi:slide
        show_icon: true
```


![image](https://user-images.githubusercontent.com/71470070/191611222-070a2f45-ceb0-4a02-9854-25f43ca7df3c.png)

**Comment by aIexus** [comment]
Why it is not possible to show icon when main entity is not defined?

**Comment by marcokreeft87** [comment]
> Why it is not possible to show icon when main entity is not defined?

Because with the icon you control the entity. If you only want to show an icon you can use hide_title: true. Its all in the wiki :)

**Comment by aIexus** [comment]
Plus I have strange error [_TypeError: t is undefined_] when I make undefined the main entity:

```
           - type: custom:room-card
             title: Hallway
             hide_title: false
             icon: mdi:door-closed-lock
            #  entity: sensor.hallway_lumi_weather_temperature
             show_icon: true
            #  tap_action: none
            #  double_tap_action: none
             entities:
               - entity: light.hallway_rgb_bulb
                 show_icon: true
                 state_color: true
                 name: Light
               - entity: binary_sensor.tapo_camera_motion
                 show_icon: true
                 state_color: true
                 hide_unavailable: true
                 name: Motion
               - entity: camera.tapo_camera_sd
                 show_icon: true
                 name: Camera
               - entity: binary_sensor.hallway_entrance_door_contact
                 show_icon: true
                 state_color: true
                 name: Door
             info_entities:
               - entity: sensor.hallway_lumi_weather_humidity
                 format: precision1
               - entity: sensor.hallway_lumi_weather_temperature
                 format: precision1
```
