### ISSUE TITLE
Receiving error:  TypeError: Cannot read properties of undefined (reading 'styles')

### ISSUE THREAD

**Issue by thewolfman56** [marcokreeft87/room-card#57]
Card was working until I updated this morning to v1.4.1.
 I was using the following code for the card.

```
type: custom:room-card
title: Pool
hide_title: false
icon: mdi:pool
show_icon: true
info_entities:
  - entity: sensor.water_sensor_1
    show_icon: false
  - entity: sensor.water_sensor_1
    show_icon: true
    icon: mdi:pool-thermometer
  - entity: binary_sensor.heat_pump
    name: Heat Pump
    show_name: true
rows:
  - entities:
      - entity: light.pool_lights_no
        name: Pool Light Group
        tap_action:
          action: toggle
        hold_action:
          action: more-info
      - entity: light.baja_light
        tap_action:
          action: toggle
      - entity: light.pool_lights
        tap_action:
          action: toggle
      - entity: light.grotto_light
        tap action: toggle
      - entity: light.waterfall_light
        name: Waterfall Lights
        tap_action:
          action: toggle
  - entities:
      - entity: switch.waterfall_scene_switch
        name: Waterfall
        icon: mdi:pool
      - entity: switch.waterfall_scene_switch
        name: Waterslide
        icon: mdi:slide

```

I tried starting a new card from a blank template.  As soon as I enter just the following code, I receive that error in the visual editor

```
type: custom:room-card
rows:
- entities:
```

I tried down-grading to v1.3.9 and still receive the same error now.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
