### ISSUE TITLE
'TypeError: t is undefined' when main entity is not defined.

### ISSUE THREAD

**Issue by aIexus** [marcokreeft87/room-card#59]
I have strange error [_TypeError: t is undefined_] when I make undefined the main entity:

```
           - type: custom:room-card
             title: Hallway
             hide_title: false
             icon: mdi:door-closed-lock
            #  entity: sensor.hallway_lumi_weather_temperature
             show_icon: true
            #  tap_action: none
            #  double_tap_action: none
             entities:
               - entity: light.hallway_rgb_bulb
                 show_icon: true
                 state_color: true
                 name: Light
               - entity: binary_sensor.tapo_camera_motion
                 show_icon: true
                 state_color: true
                 hide_unavailable: true
                 name: Motion
               - entity: camera.tapo_camera_sd
                 show_icon: true
                 name: Camera
               - entity: binary_sensor.hallway_entrance_door_contact
                 show_icon: true
                 state_color: true
                 name: Door
             info_entities:
               - entity: sensor.hallway_lumi_weather_humidity
                 format: precision1
               - entity: sensor.hallway_lumi_weather_temperature
                 format: precision1
```

_Originally posted by @aIexus in https://github.com/marcokreeft87/room-card/issues/56#issuecomment-1254637718_
