### ISSUE TITLE
Custom element doesn't exist: gauge

### ISSUE THREAD

**Issue by Parchbrot** [marcokreeft87/room-card#64]
![image](https://user-images.githubusercontent.com/4101312/192365298-1212b560-bbe5-4398-b409-783bb77c7337.png)

after fixing the "n.setConfig" bug now I got the error "Custom element doesn't exist: gauge" with this configuration:
```
type: custom:room-card
title: Solar
entity: Solar
icon: fas:solar-panel
show_icon: true
cards:
  - type: gauge
    entity: sensor.solartotalpower
    max: 300
    needle: false
    name: Aktuell
```
