### ISSUE TITLE
Could we get icons a bit more tightly packed ?

### ISSUE THREAD

**Issue by tomtom13** [marcokreeft87/room-card#76]
As in tittle: Could we get icons a bit more tightly packed ?
If one removes names from icons, those still consume significant portion of a row, and it's not possible to fit more than 6 icons per row.

**Comment by marcokreeft87** [comment]
Let's see if we can make the margin configurable. It's going on the todo list

**Comment by marcokreeft87** [comment]
I've tried to do this but its just too much work for this little feature.
I would recommend combining templates together with styles like this:

```
type: custom:room-card
title: Multiple rows
entity: switch.fordpass_ignition_switch
show_icon: true
state_color: true
tap_action:
  action: toggle
templates:
  - name: margin_template
    template:
      styles:
        margin-right: 5px
info_entities:
  - entity: sensor.node_21_air_temperature
    format: precision1
  - entity: sensor.node_21_humidity
    format: precision0
rows:
  - entities:
      - entity: switch.fordpass_ignition_switch
        name: lamp1
        state_color: true
        tap_action:
          action: toggle
        template: margin_template
      - entity: switch.fordpass_ignition_switch
        name: lamp2
        state_color: true
        tap_action:
          action: toggle
        template: margin_template
  - entities:
      - entity: switch.fordpass_ignition_switch
        name: lamp1
        state_color: true
        tap_action:
          action: toggle
        template: margin_template
      - entity: switch.fordpass_ignition_switch
        name: lamp2
        state_color: true
        tap_action:
          action: toggle
        template: margin_template

```
